"""Publish reviewed statutory content so it can drive real calendars and documents.

Plan §2.12: engineering builds the engine; a qualified Company Secretary supplies and
approves the wording. Nothing generated by this module reaches a client until a named
human has signed off on it — which is why ``--reviewer-name`` is required and there is
no default.

Two catalogues sit behind the same gate, and both are handled here: the **compliance
rules** that drive the calendar, and the **content packs** that drive generated
documents. Publishing only the rules would leave a working document engine that refuses
to produce anything, which is a confusing way to fail.

    python -m scripts.publish_secretarial_content \
        --reviewer-name "A. Sharma" --reviewer-credential "ACS 12345"

    # Publish a subset while the rest is still under review
    python -m scripts.publish_secretarial_content --reviewer-name "..." \
        --codes AGM MGT-7 AOC-4

    # One catalogue only
    python -m scripts.publish_secretarial_content --reviewer-name "..." --what packs

    # See what would change
    python -m scripts.publish_secretarial_content --reviewer-name "..." --dry-run
"""

import argparse
import asyncio
import sys
from datetime import UTC, date, datetime
from pathlib import Path

from sqlalchemy import select

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.core.database import async_session_factory  # noqa: E402
from app.models.secretarial import (  # noqa: E402
    SecretarialComplianceRule,
    SecretarialContentPack,
)

# Both catalogues carry the identical provenance columns, so one routine covers both.
CATALOGUES = {
    "rules": (SecretarialComplianceRule, "rule"),
    "packs": (SecretarialContentPack, "pack"),
}


async def _publish(db, model, noun: str, args, effective_from: date) -> int:
    stmt = select(model).where(
        model.company_id.is_(None),
        model.review_status != "published",
    )
    if args.codes:
        stmt = stmt.where(model.code.in_(args.codes))
    rows = list((await db.execute(stmt)).scalars().all())

    if not rows:
        print(f"  ({noun}s: nothing to publish — every match is already published)")
        return 0

    for row in rows:
        print(f"  {noun:5s} {row.code:26s} {row.review_status:10s} -> published   {row.title}")
        if args.dry_run:
            continue
        row.review_status = "published"
        row.reviewer_name = args.reviewer_name
        row.reviewer_credential = args.reviewer_credential
        row.reviewed_on = date.today()
        row.published_at = datetime.now(UTC)
        row.effective_from = effective_from

    return len(rows)


async def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--reviewer-name",
        required=True,
        help="Full name of the Company Secretary or legal professional who reviewed the wording.",
    )
    parser.add_argument(
        "--reviewer-credential",
        default=None,
        help="Membership or registration number, e.g. 'ACS 12345' or 'FCS 6789'.",
    )
    parser.add_argument(
        "--what",
        choices=["all", "rules", "packs"],
        default="all",
        help="Which catalogue to publish (default: both).",
    )
    parser.add_argument(
        "--codes",
        nargs="*",
        default=None,
        help="Codes to publish. Omit to publish every draft in the system catalogue.",
    )
    parser.add_argument(
        "--effective-from",
        default=None,
        help="ISO date the published version takes effect (default: today).",
    )
    parser.add_argument("--dry-run", action="store_true", help="Report without writing.")
    args = parser.parse_args()

    effective_from = (
        date.fromisoformat(args.effective_from) if args.effective_from else date.today()
    )
    wanted = list(CATALOGUES) if args.what == "all" else [args.what]

    async with async_session_factory() as db:
        total = 0
        for key in wanted:
            model, noun = CATALOGUES[key]
            total += await _publish(db, model, noun, args, effective_from)

        if total == 0:
            print("Nothing to publish.")
            return

        if args.dry_run:
            print(f"\nDry run — {total} item(s) would be published by {args.reviewer_name}.")
            return

        await db.commit()
        print(
            f"\nPublished {total} item(s), reviewed by {args.reviewer_name}"
            f"{f' ({args.reviewer_credential})' if args.reviewer_credential else ''}, "
            f"effective {effective_from.isoformat()}."
        )


if __name__ == "__main__":
    asyncio.run(main())
