"""Publish reviewed statutory content so it can drive real compliance calendars.

Plan §2.12: engineering builds the engine; a qualified Company Secretary supplies and
approves the wording. Nothing generated by this module reaches a client until a named
human has signed off on it — which is why ``--reviewer-name`` is required and there is
no default.

    python -m scripts.publish_secretarial_content \
        --reviewer-name "A. Sharma" --reviewer-credential "ACS 12345"

    # Publish a subset while the rest is still under review
    python -m scripts.publish_secretarial_content --reviewer-name "..." \
        --codes AGM MGT-7 AOC-4

    # See what would change
    python -m scripts.publish_secretarial_content --reviewer-name "..." --dry-run
"""

import argparse
import asyncio
import sys
from datetime import UTC, date, datetime
from pathlib import Path

from sqlalchemy import select

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.core.database import async_session_factory  # noqa: E402
from app.models.secretarial import SecretarialComplianceRule  # noqa: E402


async def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--reviewer-name",
        required=True,
        help="Full name of the Company Secretary or legal professional who reviewed the wording.",
    )
    parser.add_argument(
        "--reviewer-credential",
        default=None,
        help="Membership or registration number, e.g. 'ACS 12345' or 'FCS 6789'.",
    )
    parser.add_argument(
        "--codes",
        nargs="*",
        default=None,
        help="Rule codes to publish. Omit to publish every draft in the system catalogue.",
    )
    parser.add_argument(
        "--effective-from",
        default=None,
        help="ISO date the published version takes effect (default: today).",
    )
    parser.add_argument("--dry-run", action="store_true", help="Report without writing.")
    args = parser.parse_args()

    effective_from = (
        date.fromisoformat(args.effective_from) if args.effective_from else date.today()
    )

    async with async_session_factory() as db:
        stmt = select(SecretarialComplianceRule).where(
            SecretarialComplianceRule.company_id.is_(None),
            SecretarialComplianceRule.review_status != "published",
        )
        if args.codes:
            stmt = stmt.where(SecretarialComplianceRule.code.in_(args.codes))
        rules = list((await db.execute(stmt)).scalars().all())

        if not rules:
            print("Nothing to publish — every matching rule is already published.")
            return

        for rule in rules:
            print(f"  {rule.code:24s} {rule.review_status:10s} -> published   {rule.title}")
            if args.dry_run:
                continue
            rule.review_status = "published"
            rule.reviewer_name = args.reviewer_name
            rule.reviewer_credential = args.reviewer_credential
            rule.reviewed_on = date.today()
            rule.published_at = datetime.now(UTC)
            rule.effective_from = effective_from

        if args.dry_run:
            print(f"\nDry run — {len(rules)} rule(s) would be published by {args.reviewer_name}.")
            return

        await db.commit()
        print(
            f"\nPublished {len(rules)} rule(s), reviewed by {args.reviewer_name}"
            f"{f' ({args.reviewer_credential})' if args.reviewer_credential else ''}, "
            f"effective {effective_from.isoformat()}."
        )


if __name__ == "__main__":
    asyncio.run(main())
