"""The versioned legal-content layer (plan §2.12).

Statutory wording is not written by engineers and not generated by a model. It is
authored against a cited source, reviewed by a qualified professional, published, and
then **frozen** — an amendment creates a new version rather than editing the old one,
because a document generated in 2026 must still re-render under 2026's wording in 2031.

The gate is at *publish*, not at code: every slot exists from Phase 0 as a ``draft`` row
so the whole pipeline is testable end to end, and ``services.secretarial.content``
refuses to render or evaluate anything that is not ``published``.

Divergence from plan §2.10 worth recording: the catalogue lives in the public schema,
not ``statutory``. The review workflow writes ``reviewed_by``/``published_at`` from the
app, and ``statutory`` is owner-write-only by design. Tenants may also author their own
packs, which a company-less schema cannot express. ``company_id`` NULL = system
catalogue, set = tenant-authored.
"""

import uuid
from datetime import date, datetime
from typing import Any

from sqlalchemy import (
    Boolean,
    Date,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB, TIMESTAMP, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base, DocumentMixin

REVIEW_STATUSES = ("draft", "reviewed", "approved", "published", "retired")

# Only this one may be used by generation or rule evaluation.
USABLE_REVIEW_STATUS = "published"


class SecretarialContentPack(Base, DocumentMixin):
    """One event type's document set — the unit the drafting engine renders.

    ``fragments`` holds a **block tree**, not HTML (plan §2.6): heading, paragraph,
    numbered-list, table, signature-grid, page-break. Two renderers consume it — PDF in
    v1, DOCX later — and authoring in HTML now would make the DOCX renderer a rewrite of
    every pack, so the schema is enforced at load time.
    """

    __tablename__ = "secretarial_content_packs"
    __table_args__ = (
        UniqueConstraint("code", "version", "company_id", name="uq_secretarial_pack_version"),
        Index("ix_secretarial_packs_lookup", "code", "review_status"),
        Index("ix_secretarial_packs_event", "event_type"),
    )

    # NULL = system catalogue (shipped with the product, not tenant-editable).
    company_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("companies.id", ondelete="CASCADE")
    )

    code: Mapped[str] = mapped_column(String(80), nullable=False)
    version: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("1"))
    title: Mapped[str] = mapped_column(String(200), nullable=False)
    event_type: Mapped[str] = mapped_column(String(60), nullable=False)
    # Which entity kinds this pack applies to, e.g. ["company"] or ["company", "llp"].
    applies_to_kinds: Mapped[list[str] | None] = mapped_column(JSONB)

    fragments: Mapped[dict[str, Any] | None] = mapped_column(JSONB)
    variables: Mapped[list[dict[str, Any]] | None] = mapped_column(JSONB)
    # Act sections, SS refs and the filings this resolution triggers — the connective
    # tissue between generating a document and the compliance calendar (plan §6).
    compliance_meta: Mapped[dict[str, Any] | None] = mapped_column(JSONB)

    # --- Provenance and review (§2.12) -------------------------------------------
    source_ref: Mapped[str | None] = mapped_column(String(300))
    source_excerpt: Mapped[str | None] = mapped_column(Text)
    review_status: Mapped[str] = mapped_column(
        String(20), nullable=False, server_default=text("'draft'")
    )
    reviewed_by: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL")
    )
    reviewed_on: Mapped[date | None] = mapped_column(Date)
    reviewer_name: Mapped[str | None] = mapped_column(String(200))
    reviewer_credential: Mapped[str | None] = mapped_column(String(140))
    published_at: Mapped[datetime | None] = mapped_column(TIMESTAMP(timezone=True))

    effective_from: Mapped[date | None] = mapped_column(Date)
    superseded_by_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("secretarial_content_packs.id", ondelete="SET NULL")
    )
    superseded_on: Mapped[date | None] = mapped_column(Date)

    is_system: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("false"))
    notes: Mapped[str | None] = mapped_column(Text)

    @property
    def is_usable(self) -> bool:
        """Only published content may reach a client's document or calendar."""
        return self.review_status == USABLE_REVIEW_STATUS and self.superseded_by_id is None
